name: Deploy Lambda

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  OUTPUT_BUCKET: ${{ secrets.OUTPUT_BUCKET }}
  INPUT_BUCKET: ${{ secrets.INPUT_BUCKET }}
  USER_SQS_URL: ${{ secrets.USER_SQS_URL }}
  PROCESS_TRACKING_SQS_URL: ${{ secrets.PROCESS_TRACKING_SQS_URL }}
  AWS_DEFAULT_REGION: us-east-1
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
    
    - name: Upload ffmpeg dependency to infra bucket
      run: aws s3 cp ffmpeg-layer.zip s3://${TF_STATE_BUCKET}/ffmpeg-layer.zip

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=lambda.tfstate" -backend-config="region=us-east-1"
    
    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve -var "tf_state_bucket=${TF_STATE_BUCKET}" -var "output_s3_bucket=${OUTPUT_BUCKET}" -var "input_s3_bucket=${UPLOAD_DESTINATION_BUCKET}" -var "user_sqs=${USER_SQS_URL}" -var "process_tracking_sqs_url=${SQS_URL}"